/* ---------------------------------------------------------------------------
   Task list, running on mock data. Nothing here talks to the API yet: the
   shapes below mirror what GET /tasks returns so wiring it up later is a swap
   of the data source, not a rewrite of the view.

   The three filters are the backend's own states, decided the same way:
     passed    - its moment has gone by
     actual    - still ahead, and near enough to matter under its active logic
     upcoming  - still ahead, but outside that window
--------------------------------------------------------------------------- */

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const now = Date.now();
const at = (offset) => new Date(now + offset).toISOString();

/**
 * Mock tasks, one of every shape the API can return: a plain task, subtasks, a
 * hand-made event, and events generated by daily, weekly and monthly configs.
 *
 * `repeat` stands in for the config an event came from. The API returns only
 * `configTaskId` today, so a real client would need a second request to show
 * this label — which is exactly the "load the parent config with the task"
 * note sitting in fix-TODO.
 */
const tasks = [
  {
    id: "t1",
    type: "BASIC",
    name: "Buy milk",
    status: "TODO",
    subtasks: [
      { id: "s1", name: "Oat milk", status: "DONE" },
      { id: "s2", name: "Check the date", status: "TODO" },
    ],
  },
  {
    id: "t2",
    type: "EVENT",
    name: "Drink water",
    status: "TODO",
    date: at(2 * HOUR),
    activeLogic: "TODAY",
    passedDate: null,
    configTaskId: "c1",
    repeat: "Every 2h, 09:00–23:00",
    subtasks: [],
  },
  {
    id: "t3",
    type: "EVENT",
    name: "Drink water",
    status: "DONE",
    date: at(-1 * HOUR),
    activeLogic: "TODAY",
    passedDate: at(-1 * HOUR),
    configTaskId: "c1",
    repeat: "Every 2h, 09:00–23:00",
    subtasks: [],
  },
  {
    id: "t4",
    type: "EVENT",
    name: "Stretch before bed",
    status: "TODO",
    date: at(-5 * HOUR),
    activeLogic: "TODAY",
    passedDate: at(-5 * HOUR),
    configTaskId: "c2",
    repeat: "Daily",
    subtasks: [],
  },
  {
    id: "t5",
    type: "EVENT",
    name: "Dentist",
    status: "TODO",
    date: at(6 * HOUR),
    activeLogic: "NEXT_30_DAYS",
    passedDate: null,
    configTaskId: null,
    subtasks: [],
  },
  {
    id: "t6",
    type: "EVENT",
    name: "Gym",
    status: "TODO",
    date: at(4 * DAY),
    activeLogic: "THIS_WEEK",
    passedDate: null,
    configTaskId: "c3",
    repeat: "Mondays and Fridays",
    subtasks: [],
  },
  {
    id: "t7",
    type: "EVENT",
    name: "Pay rent",
    status: "TODO",
    date: at(12 * DAY),
    activeLogic: "NEXT_30_DAYS",
    passedDate: null,
    configTaskId: "c4",
    repeat: "1st of every month",
    subtasks: [],
  },
  {
    id: "t8",
    type: "EVENT",
    name: "Renew passport",
    status: "TODO",
    date: at(70 * DAY),
    activeLogic: "NEXT_30_DAYS",
    passedDate: null,
    configTaskId: null,
    subtasks: [],
  },
];

/* --- the filter rules, mirroring the backend ----------------------------- */

const startOfToday = () => { const d = new Date(); d.setHours(0, 0, 0, 0); return d; };

const endOfToday = () => { const d = new Date(); d.setHours(23, 59, 59, 999); return d; };

const endOfThisWeek = () => {
  const d = new Date();
  d.setDate(d.getDate() + ((7 - d.getDay()) % 7));
  d.setHours(23, 59, 59, 999);
  return d;
};

const endOfNext30Days = () => {
  const d = new Date(Date.now() + 30 * DAY);
  d.setHours(23, 59, 59, 999);
  return d;
};

function windowEndFor(task) {
  if (task.activeLogic === "TODAY") return endOfToday();
  if (task.activeLogic === "THIS_WEEK") return endOfThisWeek();
  return endOfNext30Days();
}

const hasDate = (task) => typeof task.date === "string";

const hasPassed = (task) => hasDate(task) && new Date(task.date) <= new Date();

function stateOf(task) {
  if (!hasDate(task)) return "actual";
  if (hasPassed(task)) return "passed";
  const date = new Date(task.date);
  return date >= startOfToday() && date <= windowEndFor(task) ? "actual" : "upcoming";
}

/* --- formatting ---------------------------------------------------------- */

const time = new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit" });
const dayAndDate = new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "numeric", month: "short" });

const startOfDayOf = (date) => {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
};

function whenLabel(task) {
  const date = new Date(task.date);
  // Calendar days apart, not hours apart: 22:00 today is still today, and
  // 09:00 tomorrow is one day away even though it is 11 hours off.
  const days = Math.round((startOfDayOf(date) - startOfToday()) / DAY);
  if (days === 0) return `Today ${time.format(date)}`;
  if (days === 1) return `Tomorrow ${time.format(date)}`;
  if (days === -1) return `Yesterday ${time.format(date)}`;
  return `${dayAndDate.format(date)} ${time.format(date)}`;
}

function subtaskLabel(task) {
  const done = task.subtasks.filter((sub) => sub.status === "DONE").length;
  return `${done}/${task.subtasks.length} steps`;
}

/* --- rendering ----------------------------------------------------------- */

const listEl = document.getElementById("list");
const summaryEl = document.getElementById("summary");
const announcer = document.getElementById("announcer");
let activeFilter = "actual";

function chip(text, modifier) {
  const el = document.createElement("span");
  el.className = modifier ? `chip chip--${modifier}` : "chip";
  el.textContent = text;
  return el;
}

function iconButton(label, glyph, onClick) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "icon-btn";
  button.setAttribute("aria-label", label);
  button.textContent = glyph;
  button.addEventListener("click", onClick);
  return button;
}

function taskItem(task) {
  const done = task.status === "DONE";
  const item = document.createElement("li");
  item.className = done ? "task task--done" : "task";

  const check = document.createElement("button");
  check.type = "button";
  check.className = "task__check";
  check.textContent = "✓";
  check.setAttribute("aria-pressed", String(done));
  check.setAttribute("aria-label", done ? `Mark ${task.name} as not done` : `Mark ${task.name} as done`);
  check.addEventListener("click", () => toggleDone(task));

  const body = document.createElement("div");
  body.className = "task__body";

  const name = document.createElement("p");
  name.className = "task__name";
  name.textContent = task.name;
  body.append(name);

  const meta = document.createElement("div");
  meta.className = "task__meta";

  if (hasDate(task)) {
    const overdue = hasPassed(task) && !done;
    let modifier = "when";
    if (overdue) modifier = "overdue";
    else if (done) modifier = "done";
    else if (stateOf(task) === "upcoming") modifier = "upcoming";
    meta.append(chip(overdue ? `Missed · ${whenLabel(task)}` : whenLabel(task), modifier));
  }

  if (task.repeat) meta.append(chip(`🔁 ${task.repeat}`, "repeat"));
  if (task.subtasks.length > 0) meta.append(chip(subtaskLabel(task)));
  if (!hasDate(task)) meta.append(chip("No date"));

  body.append(meta);

  const actions = document.createElement("div");
  actions.className = "task__actions";
  actions.append(
    iconButton(done ? `Mark ${task.name} as not done` : `Mark ${task.name} as done`, done ? "↩" : "✓", () => toggleDone(task)),
    iconButton(`Delete ${task.name}`, "🗑", () => remove(task)),
  );

  item.append(check, body, actions);
  return item;
}

function emptyState() {
  const wrap = document.createElement("li");
  wrap.className = "empty";
  const messages = {
    passed: ["🕓", "Nothing has gone by yet."],
    actual: ["🎯", "Nothing needs doing right now."],
    upcoming: ["🌱", "Nothing further out."],
  };
  const [icon, text] = messages[activeFilter];
  wrap.innerHTML = `<div class="empty__icon" aria-hidden="true">${icon}</div><p class="empty__text"></p>`;
  wrap.querySelector(".empty__text").textContent = text;
  return wrap;
}

function render() {
  const counts = { passed: 0, actual: 0, upcoming: 0 };
  tasks.forEach((task) => { counts[stateOf(task)] += 1; });

  document.querySelectorAll("[data-count]").forEach((el) => {
    el.textContent = String(counts[el.dataset.count]);
  });
  document.querySelectorAll(".filter").forEach((button) => {
    button.setAttribute("aria-pressed", String(button.dataset.state === activeFilter));
  });

  const shown = tasks.filter((task) => stateOf(task) === activeFilter);
  const left = shown.filter((task) => task.status !== "DONE").length;
  summaryEl.textContent = shown.length === 0 ? "" : `${left} of ${shown.length} left`;

  listEl.replaceChildren(...(shown.length === 0 ? [emptyState()] : shown.map(taskItem)));
}

/* --- actions ------------------------------------------------------------- */

function toggleDone(task) {
  task.status = task.status === "DONE" ? "TODO" : "DONE";
  announcer.textContent = `${task.name} marked ${task.status === "DONE" ? "done" : "not done"}`;
  render();
}

function remove(task) {
  const index = tasks.indexOf(task);
  if (index !== -1) tasks.splice(index, 1);
  announcer.textContent = `${task.name} deleted`;
  render();
}

document.querySelectorAll(".filter").forEach((button) => {
  button.addEventListener("click", () => {
    activeFilter = button.dataset.state;
    render();
  });
});

const composer = document.getElementById("composer");
const composerForm = document.getElementById("composer-form");

document.getElementById("add").addEventListener("click", () => {
  composerForm.reset();
  composer.showModal();
});

document.getElementById("composer-cancel").addEventListener("click", () => composer.close());

composerForm.addEventListener("submit", () => {
  const data = new FormData(composerForm);
  const name = String(data.get("name")).trim();
  if (name === "") return;

  const date = String(data.get("date"));
  tasks.unshift({
    id: `t${String(Date.now())}`,
    type: date ? "EVENT" : "BASIC",
    name,
    status: "TODO",
    subtasks: [],
    ...(date ? { date: new Date(date).toISOString(), activeLogic: "NEXT_30_DAYS", passedDate: null, configTaskId: null } : {}),
  });

  activeFilter = stateOf(tasks[0]);
  announcer.textContent = `${name} added`;
  render();
});

render();
