/* ---------------------------------------------------------------------------
   Task list, running on mock data. Nothing here talks to the API yet: the
   shapes below mirror what GET /tasks returns so wiring it up later is a swap
   of the data source, not a rewrite of the view.

   The three filters are the backend's own states, decided the same way:
     passed    - its moment has gone by
     actual    - still ahead, and near enough to matter under its active logic
     upcoming  - still ahead, but outside that window
--------------------------------------------------------------------------- */

/**
 * Categories, colours and icons carried over from the previous app. Each keeps
 * its fixed colour slot — adding or removing one never re-shuffles the others.
 * The neon values are only ever used mixed into the surface (see styles.css),
 * so they read as identity without breaking the pastel palette.
 */
const CATEGORIES = {
  important: { label: "Important", color: "#fb1919", icon: "⭐" },
  work: { label: "Work", color: "#13c2f9", icon: "💼" },
  supplements: { label: "Supplements", color: "#27b621", icon: "💊" },
  food: { label: "Food", color: "#ffed02", icon: "🍎" },
  education: { label: "Education", color: "#bce211", icon: "🎓" },
  selfcare: { label: "Selfcare", color: "#13d4c7", icon: "🧘" },
  gym: { label: "Gym", color: "#ff8000", icon: "🏋️" },
  reading: { label: "Reading", color: "#f5228e", icon: "📖" },
};

/** Category is optional, so tasks without one land in a neutral bucket. */
const NONE_KEY = "none";
const NONE_CATEGORY = { label: "Other", color: "#9ca3af", icon: "🗂️" };

const categoryOf = (key) => CATEGORIES[key] ?? NONE_CATEGORY;

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const now = Date.now();
const at = (offset) => new Date(now + offset).toISOString();

/**
 * Mock tasks, one of every shape the API can return: a plain task, subtasks, a
 * hand-made event, and events generated by daily, weekly and monthly configs.
 *
 * `repeat` stands in for the config an event came from. The API returns only
 * `configTaskId` today, so a real client would need a second request to show
 * this label — which is exactly the "load the parent config with the task"
 * note sitting in fix-TODO.
 */
const tasks = [
  {
    id: "t1",
    category: "food",
    type: "BASIC",
    name: "Buy milk",
    status: "TODO",
    subtasks: [
      { id: "s1", name: "Oat milk", status: "DONE" },
      { id: "s2", name: "Check the date", status: "TODO" },
    ],
  },
  {
    id: "t2",
    category: "selfcare",
    type: "EVENT",
    name: "Drink water",
    status: "TODO",
    date: at(2 * HOUR),
    activeLogic: "TODAY",
    passedDate: null,
    configTaskId: "c1",
    repeat: "Every 2h, 09:00–23:00",
    subtasks: [],
  },
  {
    id: "t3",
    category: "selfcare",
    type: "EVENT",
    name: "Drink water",
    status: "DONE",
    date: at(-1 * HOUR),
    activeLogic: "TODAY",
    passedDate: at(-1 * HOUR),
    configTaskId: "c1",
    repeat: "Every 2h, 09:00–23:00",
    subtasks: [],
  },
  {
    id: "t4",
    category: "gym",
    type: "EVENT",
    name: "Stretch before bed",
    status: "TODO",
    date: at(-5 * HOUR),
    activeLogic: "TODAY",
    passedDate: at(-5 * HOUR),
    configTaskId: "c2",
    repeat: "Daily",
    subtasks: [],
  },
  {
    id: "t5",
    category: "important",
    type: "EVENT",
    name: "Dentist",
    status: "TODO",
    date: at(6 * HOUR),
    activeLogic: "NEXT_30_DAYS",
    passedDate: null,
    configTaskId: null,
    subtasks: [],
  },
  {
    id: "t6",
    category: "gym",
    type: "EVENT",
    name: "Gym",
    status: "TODO",
    date: at(4 * DAY),
    activeLogic: "THIS_WEEK",
    passedDate: null,
    configTaskId: "c3",
    repeat: "Mondays and Fridays",
    subtasks: [],
  },
  {
    id: "t7",
    category: "important",
    type: "EVENT",
    name: "Pay rent",
    status: "TODO",
    date: at(12 * DAY),
    activeLogic: "NEXT_30_DAYS",
    passedDate: null,
    configTaskId: "c4",
    repeat: "1st of every month",
    subtasks: [],
  },
  {
    id: "t8",
    type: "EVENT",
    name: "Renew passport",
    status: "TODO",
    date: at(70 * DAY),
    activeLogic: "NEXT_30_DAYS",
    passedDate: null,
    configTaskId: null,
    subtasks: [],
  },
];

/* --- the filter rules, mirroring the backend ----------------------------- */

const startOfToday = () => { const d = new Date(); d.setHours(0, 0, 0, 0); return d; };

const endOfToday = () => { const d = new Date(); d.setHours(23, 59, 59, 999); return d; };

const endOfThisWeek = () => {
  const d = new Date();
  d.setDate(d.getDate() + ((7 - d.getDay()) % 7));
  d.setHours(23, 59, 59, 999);
  return d;
};

const endOfNext30Days = () => {
  const d = new Date(Date.now() + 30 * DAY);
  d.setHours(23, 59, 59, 999);
  return d;
};

function windowEndFor(task) {
  if (task.activeLogic === "TODAY") return endOfToday();
  if (task.activeLogic === "THIS_WEEK") return endOfThisWeek();
  return endOfNext30Days();
}

const hasDate = (task) => typeof task.date === "string";

const hasPassed = (task) => hasDate(task) && new Date(task.date) <= new Date();

function stateOf(task) {
  if (!hasDate(task)) return "actual";
  if (hasPassed(task)) return "passed";
  const date = new Date(task.date);
  return date >= startOfToday() && date <= windowEndFor(task) ? "actual" : "upcoming";
}

/* --- formatting ---------------------------------------------------------- */

const time = new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit" });
const dayAndDate = new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "numeric", month: "short" });

const startOfDayOf = (date) => {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
};

function whenLabel(task) {
  const date = new Date(task.date);
  // Calendar days apart, not hours apart: 22:00 today is still today, and
  // 09:00 tomorrow is one day away even though it is 11 hours off.
  const days = Math.round((startOfDayOf(date) - startOfToday()) / DAY);
  if (days === 0) return `Today ${time.format(date)}`;
  if (days === 1) return `Tomorrow ${time.format(date)}`;
  if (days === -1) return `Yesterday ${time.format(date)}`;
  return `${dayAndDate.format(date)} ${time.format(date)}`;
}

function subtaskLabel(task) {
  const done = task.subtasks.filter((sub) => sub.status === "DONE").length;
  return `${done}/${task.subtasks.length} steps`;
}

/* --- rendering ----------------------------------------------------------- */

const listEl = document.getElementById("list");
const summaryEl = document.getElementById("summary");
const announcer = document.getElementById("announcer");
let activeFilter = "actual";
let activeCategory = "all";

function chip(text, modifier) {
  const el = document.createElement("span");
  el.className = modifier ? `chip chip--${modifier}` : "chip";
  el.textContent = text;
  return el;
}

function iconButton(label, glyph, onClick) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "icon-btn";
  button.setAttribute("aria-label", label);
  button.textContent = glyph;
  button.addEventListener("click", onClick);
  return button;
}

function taskItem(task) {
  const done = task.status === "DONE";
  const item = document.createElement("li");
  item.className = done ? "task task--done" : "task";

  const check = document.createElement("button");
  check.type = "button";
  check.className = "task__check";
  check.textContent = "✓";
  check.setAttribute("aria-pressed", String(done));
  check.setAttribute("aria-label", done ? `Mark ${task.name} as not done` : `Mark ${task.name} as done`);
  check.addEventListener("click", () => toggleDone(task));

  const body = document.createElement("div");
  body.className = "task__body";

  const name = document.createElement("p");
  name.className = "task__name";
  name.textContent = task.name;
  body.append(name);

  const meta = document.createElement("div");
  meta.className = "task__meta";

  if (hasDate(task)) {
    const overdue = hasPassed(task) && !done;
    let modifier = "when";
    if (overdue) modifier = "overdue";
    else if (done) modifier = "done";
    else if (stateOf(task) === "upcoming") modifier = "upcoming";
    meta.append(chip(overdue ? `Missed · ${whenLabel(task)}` : whenLabel(task), modifier));
  }

  if (task.repeat) meta.append(chip(`🔁 ${task.repeat}`, "repeat"));
  if (task.subtasks.length > 0) meta.append(chip(subtaskLabel(task)));
  if (!hasDate(task)) meta.append(chip("No date"));

  body.append(meta);

  // Only delete lives here: done/undone is the round check at the start of the
  // card, and a second control for it was just a duplicate.
  const actions = document.createElement("div");
  actions.className = "task__actions";
  actions.append(iconButton(`Delete ${task.name}`, "🗑", () => remove(task)));

  item.append(check, body, actions);
  return item;
}

function emptyState() {
  const wrap = document.createElement("div");
  wrap.className = "empty";
  const messages = {
    passed: ["🕓", "Nothing has gone by yet."],
    actual: ["🎯", "Nothing needs doing right now."],
    upcoming: ["🌱", "Nothing further out."],
  };
  const [icon, text] = messages[activeFilter];
  wrap.innerHTML = `<div class="empty__icon" aria-hidden="true">${icon}</div><p class="empty__text"></p>`;
  wrap.querySelector(".empty__text").textContent = text;
  return wrap;
}

const categoriesEl = document.getElementById("categories");

function categoryButton(key, { label, icon, color }) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "category";
  button.dataset.category = key;
  button.style.setProperty("--cat", color);
  button.setAttribute("aria-pressed", String(activeCategory === key));
  button.setAttribute("aria-label", key === "all" ? "All categories" : label);
  button.title = label;
  button.innerHTML = `<span class="category__icon" aria-hidden="true"></span>`;
  button.querySelector(".category__icon").textContent = icon;
  button.addEventListener("click", () => {
    activeCategory = key;
    render();
  });
  return button;
}

function renderCategories() {
  const all = document.createElement("button");
  all.type = "button";
  all.className = "category category--all";
  all.dataset.category = "all";
  all.setAttribute("aria-pressed", String(activeCategory === "all"));
  all.setAttribute("aria-label", "All categories");
  all.title = "All categories";
  all.textContent = "All";
  all.addEventListener("click", () => {
    activeCategory = "all";
    render();
  });

  const buttons = Object.entries(CATEGORIES).map(([key, meta]) => categoryButton(key, meta));

  // "Other" earns a place only while something actually sits in it.
  const hasUncategorised = tasks.some((task) => !task.category);
  if (hasUncategorised) buttons.push(categoryButton(NONE_KEY, NONE_CATEGORY));

  categoriesEl.replaceChildren(all, ...buttons);
}

const inCategory = (task) =>
  activeCategory === "all" || (task.category ?? NONE_KEY) === activeCategory;

/** Fixed slots first, then the neutral bucket — never re-ordered by count. */
const groupOrder = [...Object.keys(CATEGORIES), NONE_KEY];

function taskGroup(key, items) {
  const { label, icon, color } = categoryOf(key === NONE_KEY ? undefined : key);

  const section = document.createElement("section");
  section.className = "group";
  section.style.setProperty("--cat", color);

  const heading = document.createElement("h3");
  heading.className = "group__title";

  const mark = document.createElement("span");
  mark.className = "group__icon";
  mark.setAttribute("aria-hidden", "true");
  mark.textContent = icon;

  const name = document.createElement("span");
  name.textContent = label;

  const count = document.createElement("span");
  count.className = "group__count";
  count.textContent = String(items.length);

  heading.append(mark, name, count);

  const list = document.createElement("ul");
  list.className = "group__items";
  list.append(...items.map(taskItem));

  section.append(heading, list);
  return section;
}

function render() {
  const counts = { passed: 0, actual: 0, upcoming: 0 };
  tasks.forEach((task) => { counts[stateOf(task)] += 1; });

  document.querySelectorAll("[data-count]").forEach((el) => {
    el.textContent = String(counts[el.dataset.count]);
  });
  document.querySelectorAll(".filter").forEach((button) => {
    button.setAttribute("aria-pressed", String(button.dataset.state === activeFilter));
  });

  renderCategories();

  const shown = tasks.filter((task) => stateOf(task) === activeFilter && inCategory(task));
  const left = shown.filter((task) => task.status !== "DONE").length;
  summaryEl.textContent = shown.length === 0 ? "" : `${left} of ${shown.length} left`;

  if (shown.length === 0) {
    listEl.replaceChildren(emptyState());
    return;
  }

  const groups = groupOrder
    .map((key) => [key, shown.filter((task) => (task.category ?? NONE_KEY) === key)])
    .filter(([, items]) => items.length > 0)
    .map(([key, items]) => taskGroup(key, items));

  listEl.replaceChildren(...groups);
}

/* --- actions ------------------------------------------------------------- */

function toggleDone(task) {
  task.status = task.status === "DONE" ? "TODO" : "DONE";
  announcer.textContent = `${task.name} marked ${task.status === "DONE" ? "done" : "not done"}`;
  render();
}

function remove(task) {
  const index = tasks.indexOf(task);
  if (index !== -1) tasks.splice(index, 1);
  announcer.textContent = `${task.name} deleted`;
  render();
}

document.querySelectorAll(".filter").forEach((button) => {
  button.addEventListener("click", () => {
    activeFilter = button.dataset.state;
    render();
  });
});

const composer = document.getElementById("composer");
const composerForm = document.getElementById("composer-form");

document.getElementById("add").addEventListener("click", () => {
  composerForm.reset();
  composer.showModal();
});

document.getElementById("composer-cancel").addEventListener("click", () => composer.close());

composerForm.addEventListener("submit", () => {
  const data = new FormData(composerForm);
  const name = String(data.get("name")).trim();
  if (name === "") return;

  const date = String(data.get("date"));
  tasks.unshift({
    id: `t${String(Date.now())}`,
    type: date ? "EVENT" : "BASIC",
    name,
    status: "TODO",
    subtasks: [],
    ...(date ? { date: new Date(date).toISOString(), activeLogic: "NEXT_30_DAYS", passedDate: null, configTaskId: null } : {}),
  });

  activeFilter = stateOf(tasks[0]);
  announcer.textContent = `${name} added`;
  render();
});

render();
