import { ActiveLogic } from '../enum/active-logic.enum.js';
import { TaskFilter } from '../enum/task-filter.enum.js';
import { TaskType } from '../enum/task-type.enum.js';
import type { EventTask, Task } from '../types/tasks.types.js';
import type { RepeatedTask } from '../types/repeated-tasks.types.js';

/**
 * Every rule behind `GET /tasks?filter=actual|passed|upcoming`, one rule per
 * function, so each case can be read and judged on its own.
 *
 * Two conventions hold throughout:
 *
 * - `now` is always passed in, never read from the clock inside a rule. That is
 *   what makes "on Saturday, Monday's event is hidden" a thing you can check.
 * - Every boundary is **UTC**. Days, weeks and the 10-day horizon all start and
 *   end at UTC midnight, so the same instant classifies identically wherever the
 *   server runs.
 * - Windows start at the start of today rather than at `now`, so an event
 *   earlier today still counts as inside the window. Whether it has already gone
 *   by is a separate question, answered by `hasDatePassed`.
 */

const MS_PER_MINUTE = 60 * 1000;
const MS_PER_DAY = 24 * 60 * MS_PER_MINUTE;
const DAYS_IN_ACTIVE_MONTH_WINDOW = 10;
const SUNDAY = 0;
const DAYS_PER_WEEK = 7;

// ── Day boundaries ─────────────────────────────────────────────────────────

/** UTC midnight at the start of `date`'s day. */
export function startOfDay(date: Date): Date {
  const start = new Date(date);
  start.setUTCHours(0, 0, 0, 0);

  return start;
}

/** The last instant of `date`'s UTC day, 23:59:59.999. */
export function endOfDay(date: Date): Date {
  const end = new Date(date);
  end.setUTCHours(23, 59, 59, 999);

  return end;
}

/**
 * The last instant of the coming Sunday, UTC — where this week stops.
 *
 * On Saturday that is tomorrow night; on Sunday it is tonight, so the weekly
 * window shrinks to a single day. (Open question Q7: is that what you want?)
 */
export function endOfThisWeek(now: Date): Date {
  const daysUntilSunday = (DAYS_PER_WEEK - now.getUTCDay() + SUNDAY) % DAYS_PER_WEEK;
  const sunday = new Date(now.getTime() + daysUntilSunday * MS_PER_DAY);

  return endOfDay(sunday);
}

/**
 * The last instant of the 10th day from today — a rolling window, deliberately
 * not the calendar month, so late in a month it reaches into the next one.
 *
 * The number lives in one constant, but it is also in the enum's name, so
 * changing it means renaming ActiveLogic and migrating what is stored.
 */
export function endOfNext10Days(now: Date): Date {
  return endOfDay(new Date(now.getTime() + DAYS_IN_ACTIVE_MONTH_WINDOW * MS_PER_DAY));
}

// ── Telling the kinds of task apart ────────────────────────────────────────

/** Event tasks are the only ones with a date, so the only ones a filter sees. */
export function isEventTask(task: Task): task is EventTask {
  return task.type === TaskType.EVENT;
}

/** Which window the events generated by a config should be judged against. */
export function activeLogicForRepeatedTask(task: RepeatedTask): ActiveLogic {
  switch (task.type) {
    case TaskType.REPEATED_DAILY:
      return ActiveLogic.TODAY;
    case TaskType.REPEATED_WEEKLY:
      return ActiveLogic.THIS_WEEK;
    case TaskType.REPEATED_MONTHLY:
      return ActiveLogic.NEXT_10_DAYS;
  }
}

// ── The three active windows, one function each ────────────────────────────

/**
 * Daily rule. At 23:30 the pending event is tomorrow 09:00, which is *not*
 * within today — so nothing is actual, which is right: today is done with.
 */
export function isWithinToday(date: Date, now: Date): boolean {
  return date >= startOfDay(now) && date <= endOfDay(now);
}

/**
 * Weekly rule. On Saturday, next Monday's event falls past the coming Sunday,
 * so it is not actual — the new week has not started. On Monday the same event
 * is inside the window.
 */
export function isWithinThisWeek(date: Date, now: Date): boolean {
  return date >= startOfDay(now) && date <= endOfThisWeek(now);
}

/**
 * Monthly rule. Rolling 10 days from today: on 19 August an event on
 * 25 August is inside (6 days out), one on 1 September is not (13 days).
 */
export function isWithinNext10Days(date: Date, now: Date): boolean {
  return date >= startOfDay(now) && date <= endOfNext10Days(now);
}

/** Dispatches an event to the window its own `activeLogic` names. */
export function isWithinActiveWindow(event: EventTask, now: Date): boolean {
  switch (event.activeLogic) {
    case ActiveLogic.TODAY:
      return isWithinToday(event.date, now);
    case ActiveLogic.THIS_WEEK:
      return isWithinThisWeek(event.date, now);
    case ActiveLogic.NEXT_10_DAYS:
      return isWithinNext10Days(event.date, now);
  }
}

// ── Passed / actual / upcoming ─────────────────────────────────────────────

/**
 * The source of truth for "gone by": the date itself, not `passedDate`. The
 * poller stamps `passedDate` up to a minute late, and a filter that trusted the
 * stamp would call a just-expired event actual until the next pass.
 */
export function hasDatePassed(date: Date, now: Date): boolean {
  return date <= now;
}

/** Whether the poller has already stamped this event as passed. */
export function isMarkedPassed(event: EventTask): boolean {
  return event.passedDate !== null;
}

/**
 * When an event stops being worth acting on: its moment plus the time it was
 * given to be dealt with.
 *
 * `activeForMins` is why a task no longer goes to Passed the same minute it is
 * announced. A reminder is least useful at exactly the point it used to
 * disappear — you are notified, and the thing you were notified about is
 * already filed under "missed".
 */
export function activeUntil(event: EventTask): Date {
  return new Date(event.date.getTime() + event.activeForMins * MS_PER_MINUTE);
}

/**
 * Spent: its window has closed. Note this is *not* `hasDatePassed` — the two
 * were one function until events gained a window of their own, and they answer
 * different questions. Generation asks whether the moment has gone by, so that
 * the next occurrence can be made; the list asks whether the user can still do
 * anything about it.
 */
export function isPassedEvent(event: EventTask, now: Date): boolean {
  return now > activeUntil(event);
}

/**
 * Worth acting on now: either its moment has arrived and its window is still
 * open, or it is still ahead and near enough to matter under its own logic.
 *
 * The first clause has to stand on its own. An event mid-window has a date in
 * the past, and every `activeLogic` window requires `date >= startOfDay(now)`
 * — so judged by the window alone, an event being worked on today would fail
 * it tomorrow and be filed under Upcoming, in the future.
 */
export function isActualEvent(event: EventTask, now: Date): boolean {
  if (isPassedEvent(event, now)) return false;

  return hasDatePassed(event.date, now) || isWithinActiveWindow(event, now);
}

/** Still ahead, and too far out to be worth showing as actual yet. */
export function isUpcomingEvent(event: EventTask, now: Date): boolean {
  return !hasDatePassed(event.date, now)
    && !isPassedEvent(event, now)
    && !isWithinActiveWindow(event, now);
}

/** Was this event produced by a repeated config, rather than by a client? */
export function isGeneratedEvent(event: EventTask): boolean {
  return event.configTaskId !== null;
}

/** All events a given config has produced so far. */
export function eventsOfConfig(tasks: Task[], configTaskId: string): EventTask[] {
  return tasks.filter(isEventTask).filter((event) => event.configTaskId === configTaskId);
}

/**
 * The one event a config is currently waiting on: generated by it, its moment
 * not yet gone by. The generator's invariant is that there is at most one.
 *
 * Deliberately `hasDatePassed` and not `isPassedEvent`. Keying this off the
 * window instead would hold the next occurrence back for the length of the
 * window, and a config that repeats more often than its window is long would
 * quietly skip occurrences — every two hours with a three-hour window would
 * yield 09:00, 13:00, 17:00 and never 11:00.
 */
export function pendingEventOfConfig(
  tasks: Task[],
  configTaskId: string,
  now: Date,
): EventTask | null {
  return eventsOfConfig(tasks, configTaskId)
    .find((event) => !hasDatePassed(event.date, now)) ?? null;
}

// ── Applying a filter to a list ────────────────────────────────────────────

/**
 * A filter names a position in time. A task with no date has none: nothing
 * makes it pass and nothing makes it wait, so it is always relevant and
 * belongs under `actual`. Leaving it out of every filter would make a plain
 * to-do invisible in an app whose list is always filtered.
 */
export function matchesTaskFilter(task: Task, filter: TaskFilter, now: Date): boolean {
  if (!isEventTask(task)) return filter === TaskFilter.ACTUAL;

  switch (filter) {
    case TaskFilter.PASSED:
      return isPassedEvent(task, now);
    case TaskFilter.ACTUAL:
      return isActualEvent(task, now);
    case TaskFilter.UPCOMING:
      return isUpcomingEvent(task, now);
  }
}

/** Entry point: no filter means the whole list, basic tasks included. */
export function filterTasks(tasks: Task[], filter: TaskFilter | undefined, now: Date): Task[] {
  if (filter === undefined) return tasks;

  return tasks.filter((task) => matchesTaskFilter(task, filter, now));
}
