import { ActiveLogic } from '../../src/enum/active-logic.enum.js';
import { TaskCategory } from '../../src/enum/task-category.enum.js';
import { TaskStatus } from '../../src/enum/task-status.enum.js';
import { TaskType } from '../../src/enum/task-type.enum.js';
import type { BasicTask, EventTask } from '../../src/types/tasks.types.js';
import type { DailyTask, MonthlyTask, TimeOfDay, WeeklyTask } from '../../src/types/repeated-tasks.types.js';
import { utc } from './time.js';

/**
 * Task builders for tests. Each takes only what the scenario cares about, so a
 * test names the date and the active logic and nothing else competes for
 * attention.
 */

const CREATED_AT = utc('2026-08-01');

/** An event due at `date`, judged by `activeLogic`. */
export function anEvent(
  name: string,
  date: string,
  activeLogic: ActiveLogic,
  overrides: Partial<EventTask> = {},
): EventTask {
  return {
    id: `event-${name}`,
    type: TaskType.EVENT,
    status: TaskStatus.TODO,
    name,
    createdAt: CREATED_AT,
    category: TaskCategory.OTHER,
    links: [],
    subtasks: [],
    date: utc(date),
    activeLogic,
    passedDate: null,
    configTaskId: 'config-1',
    ...overrides,
  };
}

/** An event generated by a daily config, so judged against TODAY. */
export function aDailyEvent(name: string, date: string): EventTask {
  return anEvent(name, date, ActiveLogic.TODAY);
}

/** An event generated by a weekly config, so judged against THIS_WEEK. */
export function aWeeklyEvent(name: string, date: string): EventTask {
  return anEvent(name, date, ActiveLogic.THIS_WEEK);
}

/** An event generated by a monthly config, so judged against NEXT_30_DAYS. */
export function aMonthlyEvent(name: string, date: string): EventTask {
  return anEvent(name, date, ActiveLogic.NEXT_30_DAYS);
}

/** An event a client created directly, with no config behind it. */
export function aHandMadeEvent(name: string, date: string, activeLogic: ActiveLogic): EventTask {
  return anEvent(name, date, activeLogic, { configTaskId: null });
}

export function aBasicTask(name: string): BasicTask {
  return {
    id: `basic-${name}`,
    type: TaskType.BASIC,
    status: TaskStatus.TODO,
    name,
    createdAt: CREATED_AT,
    category: TaskCategory.OTHER,
    links: [],
    subtasks: [],
  };
}

export function aWeeklyConfig(
  name: string,
  weekdays: number[],
  overrides: Partial<WeeklyTask> = {},
): WeeklyTask {
  return {
    id: `config-${name}`,
    type: TaskType.REPEATED_WEEKLY,
    name,
    createdAt: CREATED_AT,
    category: TaskCategory.OTHER,
    links: [],
    weekdays,
    ...overrides,
  };
}

/** '09:30' becomes { hour: 9, minute: 30 } — readable schedules in tests. */
export function timeOfDay(clock: string): TimeOfDay {
  const [hour, minute] = clock.split(':').map(Number);

  return { hour: hour ?? 0, minute: minute ?? 0 };
}

export function aDailyConfig(
  name: string,
  schedule: { startsAt: string; endsAt: string; repeatEach: string },
): DailyTask {
  return {
    id: `config-${name}`,
    type: TaskType.REPEATED_DAILY,
    name,
    createdAt: CREATED_AT,
    category: TaskCategory.OTHER,
    links: [],
    startsAt: timeOfDay(schedule.startsAt),
    endsAt: timeOfDay(schedule.endsAt),
    repeatEach: timeOfDay(schedule.repeatEach),
  };
}

export function aMonthlyConfig(
  name: string,
  schedule: { fromDay: number; toDay: number; months: number[] },
): MonthlyTask {
  return {
    id: `config-${name}`,
    type: TaskType.REPEATED_MONTHLY,
    name,
    createdAt: CREATED_AT,
    category: TaskCategory.OTHER,
    links: [],
    ...schedule,
  };
}
